{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "a0080120-e061-4dc6-abd0-c3545bb52b35",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2025-09-02 20:27:44.058 \n",
      "  \u001b[33m\u001b[1mWarning:\u001b[0m to view this Streamlit app on a browser, run it with the following\n",
      "  command:\n",
      "\n",
      "    streamlit run D:\\Users\\Vinee\\anaconda3\\Lib\\site-packages\\ipykernel_launcher.py [ARGUMENTS]\n"
     ]
    }
   ],
   "source": [
    "import streamlit as st\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "import joblib\n",
    "import os\n",
    "\n",
    "# --- Model Loading ---\n",
    "# This function is cached, so it only runs once, making the app fast.\n",
    "@st.cache_resource\n",
    "def load_models():\n",
    "    \"\"\"\n",
    "    Loads all the saved model files and the training columns from disk.\n",
    "    \"\"\"\n",
    "    models_path = 'models'\n",
    "    if not os.path.exists(models_path):\n",
    "        st.error(\"`models` directory not found. Please run the `01_save_models_and_columns.py` script first.\")\n",
    "        return None, None\n",
    "\n",
    "    # Load the column layout the models were trained on\n",
    "    try:\n",
    "        train_cols = joblib.load(os.path.join(models_path, 'training_columns.joblib'))\n",
    "    except FileNotFoundError:\n",
    "        st.error(\"`training_columns.joblib` not found. Please run the saving script.\")\n",
    "        return None, None\n",
    "        \n",
    "    # Load each expert model\n",
    "    expert_models = {}\n",
    "    statuses = ['Salaried', 'Self-Employed', 'Student', 'Unemployed']\n",
    "    for status in statuses:\n",
    "        try:\n",
    "            model_path = os.path.join(models_path, f\"expert_model_{status}.joblib\")\n",
    "            expert_models[status] = joblib.load(model_path)\n",
    "        except FileNotFoundError:\n",
    "            st.error(f\"Model file for '{status}' not found. Please ensure all models were saved.\")\n",
    "            return None, None\n",
    "            \n",
    "    return expert_models, train_cols\n",
    "\n",
    "# --- Main Dashboard UI ---\n",
    "st.set_page_config(page_title=\"Default Risk Predictor\", layout=\"wide\")\n",
    "st.title(\"⚡ Interactive Default Risk Dashboard\")\n",
    "st.write(\"This app uses your pre-trained models to provide instant predictions based on customer data.\")\n",
    "\n",
    "# Load the models and column data\n",
    "trained_models, train_columns = load_models()\n",
    "\n",
    "# Sidebar for user inputs\n",
    "st.sidebar.header(\"Enter Customer Information\")\n",
    "\n",
    "# Only show inputs if models were loaded successfully\n",
    "if trained_models is not None:\n",
    "    # --- Input Fields for all features in your dataset ---\n",
    "    st.sidebar.subheader(\"Personal & Loan Details\")\n",
    "    employment_status = st.sidebar.selectbox('Employment Status', ('Salaried', 'Self-Employed', 'Student', 'Unemployed'))\n",
    "    age = st.sidebar.slider('Age', 18, 70, 35)\n",
    "    income = st.sidebar.number_input('Annual Income (INR)', min_value=0, value=500000, step=10000)\n",
    "    loan_amount = st.sidebar.number_input('Loan Amount (INR)', min_value=1, value=100000, step=10000)\n",
    "    tenure_months = st.sidebar.number_input('Loan Tenure (Months)', min_value=1, value=24, step=1)\n",
    "    interest_rate = st.sidebar.slider('Interest Rate (%)', 1.0, 30.0, 12.5, 0.5)\n",
    "    location = st.sidebar.selectbox('Location', ('Urban', 'Semi-Urban', 'Rural'))\n",
    "    loan_type = st.sidebar.selectbox('Loan Type', ('Personal Loan', 'Home Loan', 'Education Loan', 'Business Loan', 'Vehicle Loan'))\n",
    "\n",
    "    st.sidebar.subheader(\"Behavioral & History Data\")\n",
    "    missed_payments = st.sidebar.number_input('Number of Missed Payments', min_value=0, value=0)\n",
    "    partial_payments = st.sidebar.number_input('Number of Partial Payments', min_value=0, value=1)\n",
    "    delay_days = st.sidebar.number_input('Total Days Delayed', min_value=0, value=0)\n",
    "    interaction_attempts = st.sidebar.number_input('Number of Interaction Attempts', min_value=0, value=5)\n",
    "    sentiment_score = st.sidebar.slider('Average Sentiment Score', -1.0, 1.0, 0.2, 0.1)\n",
    "    response_time_hours = st.sidebar.number_input('Average Response Time (Hours)', min_value=0, value=24)\n",
    "    app_usage_frequency = st.sidebar.number_input('App Usage Frequency Score', min_value=0, value=10)\n",
    "    website_visits = st.sidebar.number_input('Number of Website Visits', min_value=0, value=3)\n",
    "    complaints = st.sidebar.number_input('Number of Complaints Registered', min_value=0, value=0)\n",
    "\n",
    "\n",
    "    # Prediction Button\n",
    "    if st.sidebar.button(\"Calculate Default Probability\"):\n",
    "        \n",
    "        # --- Create Engineered Features from Inputs ---\n",
    "        debt_to_income = loan_amount / income if income > 0 else 0\n",
    "        repayment_score = missed_payments * 3 + partial_payments * 1 + delay_days * 0.2\n",
    "        interaction_effectiveness = sentiment_score / interaction_attempts if interaction_attempts > 0 else 0\n",
    "        \n",
    "        # Create a dictionary with all base and engineered features\n",
    "        input_data = {\n",
    "            'Age': [age], 'Income': [income], 'LoanAmount': [loan_amount], 'TenureMonths': [tenure_months],\n",
    "            'InterestRate': [interest_rate], 'MissedPayments': [missed_payments], 'PartialPayments': [partial_payments],\n",
    "            'DelaysDays': [delay_days], 'InteractionAttempts': [interaction_attempts], 'SentimentScore': [sentiment_score],\n",
    "            'ResponseTimeHours': [response_time_hours], 'AppUsageFrequency': [app_usage_frequency],\n",
    "            'WebsiteVisits': [website_visits], 'Complaints': [complaints],\n",
    "            'Debt_to_Income_Ratio': [debt_to_income], 'Repayment_Score': [repayment_score],\n",
    "            'Interaction Effectiveness': [interaction_effectiveness],\n",
    "            f'Location_{location}': [1], f'LoanType_{loan_type}': [1], f'EmploymentStatus_{employment_status}': [1]\n",
    "        }\n",
    "        input_df = pd.DataFrame(input_data)\n",
    "        \n",
    "        # Align columns with the training data to ensure order and presence match\n",
    "        input_df_aligned = input_df.reindex(columns=train_columns, fill_value=0)\n",
    "        \n",
    "        # Select the correct expert model based on employment status\n",
    "        expert_pipeline = trained_models[employment_status]\n",
    "\n",
    "        # Prepare features for prediction (drop the one-hot encoded employment columns)\n",
    "        employment_dummies = ['EmploymentStatus_Salaried', 'EmploymentStatus_Self-Employed', 'EmploymentStatus_Unemployed', 'EmploymentStatus_Student']\n",
    "        features_to_predict = input_df_aligned.drop(employment_dummies, axis=1)\n",
    "\n",
    "        # Make the prediction\n",
    "        probability = expert_pipeline.predict_proba(features_to_predict)[:, 1][0]\n",
    "        \n",
    "        # Display the result\n",
    "        st.subheader(\"Prediction Result\")\n",
    "        prob_percentage = probability * 100\n",
    "        \n",
    "        if prob_percentage >= 50:\n",
    "            st.error(f\"High Risk: {prob_percentage:.2f}% Probability of Default\")\n",
    "        else:\n",
    "            st.success(f\"Low Risk: {prob_percentage:.2f}% Probability of Default\")\n",
    "        \n",
    "        st.progress(probability)\n",
    "        st.write(f\"The model for **{employment_status}** customers was used for this prediction.\")\n",
    "else:\n",
    "    st.warning(\"Could not load models. Please ensure the `models` directory exists and run the saving script.\")\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "2c7f89c8-ceda-4487-8218-f322b3938972",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
